version: '3.3'

services:
  weekcook-datapotal:
    image: weekcookregistry.azurecr.io/weekcook-recipe-analyze:v0.0.1
    restart: always
    ports:
      - "8080:8080"
  kytea-api-server:
    image: weekcookregistry.azurecr.io/kytea-api-server:v0.0.1
    restart: always
    ports:
      - "5000:5000"
