version: '3.3'

services:
  weekcook-datapotal:
    image: sampleweekcookregistory.azurecr.io/weekcook-datapotal-compose:v0.0.1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kytea-api-server
    environment:
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=*
      - http.cors.allow-headers=*
  kytea-api-server:
    image: weekcookregistry.azurecr.io/kytea-api-server:v0.0.1
    restart: always
