apiVersion: v1
kind: Service
metadata:
  name: weekcook-datapotal
  labels:
    app: weekcook-datapotal

spec:
  type: LoadBalancer
  ports:
    - name: datapotal
      protocol: TCP
      port: 8080
    - name: kytea
      protocol: TCP
      port: 5000
  selector:
    app: weekcook-datapotal
